######################################################################
# Automatically generated by qmake (2.01a) lun dic 15 14:30:15 2014
######################################################################

QT       += core gui

CONFIG += console

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = QtTutorial
DEPENDPATH += . lib lib/view
INCLUDEPATH += . lib/view

# Input
HEADERS += lib/view/mainwindow.h

FORMS += lib/view/mainwindow.ui

SOURCES += lib/main.cpp\
           lib/view/mainwindow.cpp

OTHER_FILES += \
               README.md \
               doc/VERSION_LOG
